// tienda_ropa1.FrontendReact/src/app/empleados/page.tsx
import { api } from "@/lib/api";

export default async function EmpleadosPage() {
    const empleados = await api.getEmpleados();

    return (
        <>
            <h1>Empleados</h1>
            {empleados.length > 0 ? (
                <table>
                    <thead>
                        <tr><th>Nombre</th><th>Email</th><th>Cargo</th><th style={{textAlign:"center"}}>Ventas</th></tr>
                    </thead>
                    <tbody>
                        {empleados.map((e: any) => (
                            <tr key={e.id}>
                                <td><strong>{e.nombreCompleto}</strong></td>
                                <td>{e.email ?? "—"}</td>
                                <td>{e.cargo ?? "—"}</td>
                                <td style={{textAlign:"center"}}>{e.cantidadVentas}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            ) : (
                <p style={{color:"#888"}}>No hay empleados.</p>
            )}
        </>
    );
}

// tienda_ropa1.FrontendAngular/src/app/pages/empleados.component.ts
import { Component, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ApiService } from "../services/api.service";

@Component({
    selector: "app-empleados",
    standalone: true,
    imports: [CommonModule],
    template: `
        <h1>Empleados</h1>
        <table *ngIf="empleados.length">
            <thead><tr><th>Nombre</th><th>Email</th><th>Cargo</th><th style="text-align:center">Ventas</th></tr></thead>
            <tbody>
                <tr *ngFor="let e of empleados">
                    <td><strong>{{ e.nombreCompleto }}</strong></td>
                    <td>{{ e.email ?? '—' }}</td>
                    <td>{{ e.cargo ?? '—' }}</td>
                    <td style="text-align:center">{{ e.cantidadVentas }}</td>
                </tr>
            </tbody>
        </table>
        <p *ngIf="!empleados.length" style="color:#888">No hay empleados.</p>
    `
})
export class EmpleadosComponent implements OnInit {
    empleados: any[] = [];
    constructor(private api: ApiService) {}
    ngOnInit() { this.api.getEmpleados().subscribe(e => this.empleados = e); }
}
