// tienda_ropa1.FrontendVue/src/views/Empleados.vue
<template>
    <div>
        <h1>Empleados</h1>
        <table v-if="empleados.length">
            <thead><tr><th>Nombre</th><th>Email</th><th>Cargo</th><th style="text-align:center">Ventas</th></tr></thead>
            <tbody>
                <tr v-for="e in empleados" :key="e.id">
                    <td><strong>{{ e.nombreCompleto }}</strong></td>
                    <td>{{ e.email ?? '—' }}</td>
                    <td>{{ e.cargo ?? '—' }}</td>
                    <td style="text-align:center">{{ e.cantidadVentas }}</td>
                </tr>
            </tbody>
        </table>
        <p v-else style="color:#888">No hay empleados.</p>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
const empleados = ref<any[]>([]);
onMounted(async () => {
    const res = await fetch("http://localhost:5000/api/empleados");
    empleados.value = await res.json();
});
</script>

// tienda_ropa1.FrontendReact/src/app/empleados/page.tsx
import { api } from "@/lib/api";

export default async function EmpleadosPage() {
    const empleados = await api.getEmpleados();

    return (
        <>
            <h1>Empleados</h1>
            {empleados.length > 0 ? (
                <table>
                    <thead>
                        <tr><th>Nombre</th><th>Email</th><th>Cargo</th><th style={{textAlign:"center"}}>Ventas</th></tr>
                    </thead>
                    <tbody>
                        {empleados.map((e: any) => (
                            <tr key={e.id}>
                                <td><strong>{e.nombreCompleto}</strong></td>
                                <td>{e.email ?? "—"}</td>
                                <td>{e.cargo ?? "—"}</td>
                                <td style={{textAlign:"center"}}>{e.cantidadVentas}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            ) : (
                <p style={{color:"#888"}}>No hay empleados.</p>
            )}
        </>
    );
}
